
export const WEIGHTS = {
  REQUIREMENT_MATCH: 0.30,
  SITUATION_RELEVANCE: 0.25,
  COST_EFFICIENCY: 0.20,
  TIMELINE_FEASIBILITY: 0.15,
  COMPLETENESS: 0.10
};

export const CATEGORIES = [
  'IT Services',
  'Construction',
  'Medical Equipment',
  'Office Supplies',
  'Marketing & PR',
  'Energy & Utilities',
  'Logistics',
  'Consulting'
];

export const CURRENCIES: Record<string, { symbol: string; label: string }> = {
  USD: { symbol: '$', label: 'USD ($)' },
  EUR: { symbol: '€', label: 'EUR (€)' },
  GBP: { symbol: '£', label: 'GBP (£)' },
  JPY: { symbol: '¥', label: 'JPY (¥)' },
  INR: { symbol: '₹', label: 'INR (₹)' }
};

export const LANGUAGE_CURRENCY_MAP: Record<string, string> = {
  EN: 'USD',
  HI: 'INR',
  ES: 'EUR',
  FR: 'EUR'
};

export const TRANSLATIONS: Record<string, any> = {
  EN: {
    paymentMode: "Payment Mode",
    preDelivery: "Pre-delivery",
    afterDelivery: "After-delivery",
    featureScores: "Feature Breakdown (Scale 0-10)",
    dashboard: "Dashboard",
    marketplace: "Active Marketplace",
    myPortal: "My Procurement Portal",
    newTender: "New Tender",
    tenderTitle: "Tender Title",
    category: "Category",
    budget: "Budget",
    closingTime: "Closing Time",
    status: "Status",
    processBids: "Process Bids",
    viewReport: "View Report",
    viewResults: "View Market Results",
    chat: "Chat",
    submitBid: "Submit Bid",
    switchRole: "Switch Role",
    logout: "Logout",
    welcome: "Welcome to STEP",
    signIn: "Sign In",
    signUp: "Sign Up",
    createAccount: "Create Account",
    requirements: "Requirements",
    situation: "Situation / Use Case",
    publishTender: "Publish Tender",
    cancel: "Cancel",
    solution: "Solution Description",
    fit: "Why it fits",
    price: "Quotation Price",
    timeline: "Timeline",
    submitFinalBid: "Submit Final Bid",
    aiReport: "AI Evaluation Report",
    publicLeaderboard: "Public Transparency Leaderboard",
    Buyer: "Buyer",
    Vendor: "Vendor",
    requiredDays: "Days Required",
    requiredBy: "Required By (Date)",
    features: "Features & Requirements",
    addFeature: "Add Feature",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    bidsApplied: "Bids Applied"
  },
  HI: {
    paymentMode: "भुगतान का तरीका",
    preDelivery: "डिलीवरी से पहले",
    afterDelivery: "डिलीवरी के बाद",
    featureScores: "विशेषता विवरण (स्केल 0-10)",
    dashboard: "डैशबोर्ड",
    marketplace: "सक्रिय बाज़ार",
    myPortal: "मेरा खरीद पोर्टल",
    newTender: "नई निविदा",
    tenderTitle: "निविदा शीर्षक",
    category: "श्रेणी",
    budget: "बजट",
    closingTime: "समाप्ति समय",
    status: "स्थिति",
    processBids: "बोलियों को प्रोसेस करें",
    viewReport: "रिपोर्ट देखें",
    viewResults: "बाज़ार परिणाम देखें",
    chat: "चैट",
    submitBid: "बोली लगाएं",
    switchRole: "भूमिका बदलें",
    logout: "लॉगआउट",
    welcome: "STEP में स्वागत है",
    signIn: "साइन इन करें",
    signUp: "साइन अप करें",
    createAccount: "खाता बनाएं",
    requirements: "आवश्यकताएं",
    situation: "स्थिति / उपयोग का मामला",
    publishTender: "निविदा प्रकाशित करें",
    cancel: "रद्द करें",
    solution: "समाधान विवरण",
    fit: "यह क्यों उपयुक्त है",
    price: "उद्धरण मूल्य",
    timeline: "समयरेखा",
    submitFinalBid: "अंतिम बोली जमा करें",
    aiReport: "AI मूल्यांकन रिपोर्ट",
    publicLeaderboard: "सार्वजनिक पारदर्शिता लीडरबोर्ड",
    Buyer: "खरीदार",
    Vendor: "विक्रेता",
    requiredDays: "आवश्यक दिन",
    requiredBy: "तक आवश्यक (तिथि)",
    features: "विशेषताएं और आवश्यकताएं",
    addFeature: "विशेषता जोड़ें",
    priority: "प्राथमिकता",
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    bidsApplied: "लागू बोलियाँ"
  }
};
